### ISSUE TITLE
There is a bug with the state computation (See attached screenshot)

### ISSUE THREAD

**Issue by bolah2009** [wathigo/Calculator#8]
Let's fix this bug.

The `AC` button should clear the state. With the below screenshot when I click `=` button the app crashes. Same with the `-/+` button that needs to alternate the sign of the `next` and `total` value.

As I suggested earlier moving all the logic would help solve this more painlessly. You can check which button is clicked in the `calculate` function to know the object to return as the new state.

The `state` of the image below is:  `{total: -8, next: "0989", operation: "+/-", result: "1 AC 8 +/- 989"}`

![image](https://user-images.githubusercontent.com/36057474/71574464-15389e00-2ae9-11ea-8f10-bd40380eae8f.png)

_Originally posted by @bolah2009 in https://github.com/wathigo/Calculator/pull/7_

**Comment by wathigo** [comment]
Hi @bolah2009 . 
The issue has been fixed.
