### ISSUE TITLE
:bug: The `+/-` button is not working as it should.

### ISSUE THREAD

**Issue by bolah2009** [wathigo/Calculator#9]
:bug: The `+/-` button is not working as it should.

The sign is not capturing correctly the values that are intended to alternate at times.

For example, when two numbers (or more) are clicked neither `total` nor `next` keeps track of these values. Instead, `result` seems to be the one keeping track of the changes. Here `result` is overwritten by `total` that is not keeping track of the value.
So when `55` is displayed for example it turns to `-5` when the `+/-` button is clicked.

See image below to see step to reproduce the bug. (You can also log the `state` value in the `render` method of the `App` component for more insight)

![cal-error2](https://user-images.githubusercontent.com/36057474/71619351-53ef5680-2bc4-11ea-96ed-d528b504dceb.gif)

_Originally posted by @bolah2009 in https://github.com/wathigo/Calculator/pull/7_

**Comment by wathigo** [comment]
Nice catch. The issue has been fixed @bolah2009
